In [11]:
import numpy as np

In [12]:
# Матрица значений критериев для каждого решения из таблицы 3
criterion_matrix = np.array([[40, 50, 57],   # X1
                             [44, 39, 57],   # X2
                             [37, 33, 49],   # X3
                             [42, 43, 53],   # X4
                             [47, 40, 49]])  # X5

In [13]:
def filter_solutions(criterion_matrix):
    filtered = [] # начало с первого решения
    
    for i in range(len(criterion_matrix)):
        candidate_solution = criterion_matrix[i]
        dominated = False # Сигнал для недоминирующих решений

        for j in range(len(filtered)):  # Проверка доминирования: сравниваем с уже отфильтрованными решениями
            existing_solution = filtered[j]
            # Если текущее решение хуже или равно по всем критериям, оно доминируется
            if (candidate_solution[0] <= existing_solution[0] and
                candidate_solution[1] <= existing_solution[1] and
                candidate_solution[2] <= existing_solution[2]):
                dominated = True
                break
            # Если текущее решение лучше по всем критериям, то старое удаляем
            if (candidate_solution[0] >= existing_solution[0] and
                candidate_solution[1] >= existing_solution[1] and
                candidate_solution[2] >= existing_solution[2]):
                filtered[j] = candidate_solution
                dominated = True
                break
        
        if not dominated: # Если решение не доминируется, добавляем его в список
            filtered.append(candidate_solution)
    
    return np.array(filtered)

In [14]:
optimal_solutions = filter_solutions(criterion_matrix) # Фильтрация решений

In [15]:
#[40, 50, 57],   # X1
#[44, 39, 57],   # X2
#[37, 33, 49],   # X3
#[42, 43, 53],   # X4
#[47, 40, 49]])  # X5

print(f'Оптимальные решения:\n{optimal_solutions}')

Оптимальные решения:
[[40 50 57]
 [44 39 57]
 [42 43 53]
 [47 40 49]]
